# Values formatted like "_env:YESOD_ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:YESOD_STATIC_DIR:static"
host:           "_env:YESOD_HOST:*4" # any IPv4 host
port:           "_env:YESOD_PORT:3000" # NB: The port `yesod devel` uses is distinct from this value. Set the `yesod devel` port from the command line.
ip-from-header: "_env:YESOD_IP_FROM_HEADER:false"

# Default behavior: determine the application root from the request headers.
# Uncomment to set an explicit approot
#approot:        "_env:YESOD_APPROOT:http://localhost:3000"

# By default, `yesod devel` runs in development, and built executables use
# production settings (see below). To override this, use the following:
#
# development: false

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false
# auth-dummy-login : false

# NB: If you need a numeric value (e.g. 123) to parse as a String, wrap it in single quotes (e.g. "_env:YESOD_PGPASS:'123'")
# See https://github.com/yesodweb/yesod/wiki/Configuration#parsing-numeric-values-as-strings

database:
  # See config/test-settings.yml for an override during tests
  database: "_env:YESOD_SQLITE_DATABASE:myfunactivitydb.sqlite3"
  poolsize: "_env:YESOD_SQLITE_POOLSIZE:10"

copyright: Insert copyright statement here
#analytics: UA-YOURCODE

myUser: "josedev"
publicKey: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwDnpeuNeC7EvycDffO4R\nc6CcLWLQNXiAljNv/Nf32YET7j5qG2dlxBKSTrj+/HpOBwLnl2KniITVuaIqMezs\nBKgu/VYtIm0yQt2Gz7fGTX3OtqwZswe030obsfvXWkZJTODRBbe7NijuEI1dq2Mk\nPyd8DS2iFUi2kT8QMlmNekX0jT64vRKt26/o/Kn9QGBIEXz1Yobyms/13JO0vTke\nhs6ewD7VrfBvP7ysWwOOqqVKmXQ3azZQn7ToW/RXjJ7GXrBmp5qM8ts+DIF3P5k8\nS/gCd87jKlLMrqQ4dIu18+Tv39nIn1mJSo47vpgFRA57xewC4/FwfPpDdchDWsrY\nJQIDAQAB\n-----END PUBLIC KEY-----\n"
